var MSG = {
  title: "PuzzleMaker - 定义新的编程方式",
  blocks: "拼图",
  badCode: "程序错误：\n%1",
  timeout: "超过最大执行行数。",
  trashTooltip: "清空所有拼图(危险)",
  downloadTooltip: "下载拼图布局到本地",
  saveTooltip: "上传代码到该槽位",
  loadTooltip: "载入本地的拼图布局文件",
  temporaryTooltip: "保存到浏览器缓存",
  addTooltip: "插入本地的拼图布局文件",
  docTooltip: "打开帮助文档",
  pullTooltip:"从该槽位载入代码",
  switchTooltip:"启/禁用相应插件槽位",
  catLogic: "逻辑",
  catLoops: "循环",
  catcqcode: "CQ码",
  catcqevent: "CQ事件",
  catvoiceera: "语音时代",
  catjson: "Json",
  catcqfunc: "CQ程序",
  catMath: "数学",
  catText: "文本",
  catLists: "列表",
  catColour: "颜色",
  catTime: "时间",
  catVariables: "变量",
  catFunctions: "函数",
  catsysdisk: "磁盘操作",
  listVariable: "列表",
  textVariable: "文本",
  hashError: "对不起，没有任何已保存的程序对应'%1' 。",
  xmlError: "无法载入您保存的文件。您是否使用其他版本的Blockly创建该文件的？",
  badXml: "XML解析错误：\n%1\n\n选择“确定”以取消您对XML的修改，或选择“取消”以继续编辑XML。",
  WorkspaceIsEmpty: "哎呀？你确定你的拼图区域有东西吗" + face.doge,
  OperatingCancel: "你取消了该操作...",
  DownloadFileTitle: "输入想保存的文件名(不带后缀)",
  DownloadFileSuccessful: "成功生成拼图布局文件，文件名为：",
  LoadFileSuccessful: "成功载入拼图布局文件，共计 %1 个拼图。",
  addFileSuccessful: "成功插入拼图布局文件，共计 %1 个拼图。",
  DeleteBlocksSuccessful: "成功删除 %1 块拼图",
  SaveTemporarySuccessful: "成功将当前拼图布局缓存到浏览器，共计 %1 个字节。",
  AutoSaveTemporarySuccessful: "自动缓存当前拼图布局到浏览器，共计 %1 个字节。",
  ReadTemporarySuccessful: "成功从浏览器缓存提取拼图布局，共计 %1 个拼图。",
  AllPuzzleWarning: "目前的拼图数量 %1块 超出正常值(可能导致浏览器卡顿)",
  AllPuzzleError: "目前的拼图数量 %1块 严重超出正常值(将导致浏览器卡顿)",
  LoadFileWarning: "导入文件的大小 %1字节 超出正常值(可能导致浏览器卡顿)",
  LoadFileError: "导入文件的大小 %1字节 严重超出正常值(将导致浏览器卡顿)",
  LoginError:"请点击登录按钮，重新确认您的身份",
  LoginSuccessful: "欢迎，%1",
  LoginoutSuccessful:"退出成功",
  NotLoggedIn:"未登录，请登录后继续操作",
  UploadSuccessful:"代码上传完成，你的唯一绑定码为：<br /><br />%1",
  UploadFail:"代码上传失败，请稍后再试。",
  PidExceed:"你的插件数量已经到达上限", 
  NoPid:"你没有选择保存到哪个插件槽位",
  Uploading:"代码正在上传中...",
  pulling:"正在从服务器拉取代码...",
  pullSuccessful:"成功从服务器拉取代码，共计 %1 个拼图。",
  pullError:"拉取代码发生错误，请稍后再试",
  pullEmpty:"这个槽位是空的，服务器酱没有找到任何拼图数据",
  NoCQEvent:"代码中缺少酷Q事件<br/><br/>代码可以保存,但无法运行",
  CodehasMistake:"没有生成有效的代码，可能存在积木拼接不完整的情况。<br/><br/>但仍然可以保存。",
  redsanjiao:"注意所有拼图都要在CQ事件或函数中<br/><br/>代码无法保存",
  ChooseFirst:"请先选择要载入/上传的代码槽位",
  slotTEMP:"已经定位到浏览器本地缓存",
  slotNoTEMP:"已经定位到 插件槽位%1",
  addingDemo:"获取实例 %1 内容中...",
  addDemoSuccessful:"插件实例 %1 被载入到编辑器中",
  demo_likedemo:"名片赞实例",
  demo_adkillerdemo:"广告检测插件实例"
};
